### ISSUE TITLE
Cover Ambience transparent text outline (customization)

### ISSUE THREAD

**Issue by Ay-CC** [Theblockbuster1/spicetify-extensions#21]
The text with some colors can get very hard to read, so a simple outline helps that a lot.
I even wrote you up the code that does this and added support using genres aswell.

```css
/* Add outlines to song text / artist / genre */
.main-trackInfo-name
{
  text-shadow: -1px -1px 0 #121212, 1px -1px 0 #121212, -1px 1px 0 #121212, 1px 1px 0 #121212;
}

.main-trackInfo-artists
{
  text-shadow: -1px -1px 0 #2A2A2A, 1px -1px 0 #2A2A2A, -1px 1px 0 #2A2A2A, 1px 1px 0 #2A2A2A;
 }

.main-trackInfo-genres
{
  text-shadow: -1px -1px 0 #2A2A2A, 1px -1px 0 #2A2A2A, -1px 1px 0 #2A2A2A, 1px 1px 0 #2A2A2A;  
}
```
